### ISSUE TITLE
bpp-seq-omics

### ISSUE THREAD

**Issue by hbadrane** [BioPP/bpp-phyl-omics#5]
Hello,

I installed and compiled successfully bpp-core, bpp-seq, bpp-popgen, bpp-phyl, bpp-seq-omics (all in same day). But couldn't compile bpp-phy-omics, it doesn't seem to find or recongnize the installation of bpp-seq-omics:
cmake -DCMAKE_INSTALL_PREFIX=path_to_bpp/BPP
-- The CXX compiler identification is GNU 8.2.0
-- Check for working CXX compiler: /ihome/crc/install/gcc/8.2.0/bin/c++
-- Check for working CXX compiler: /ihome/crc/install/gcc/8.2.0/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:66 (find_package):
  By not providing "Findbpp-seq-omics.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "bpp-seq-omics", but CMake did not find one.

  Could not find a package configuration file provided by "bpp-seq-omics"
  (requested version 3.0.0) with any of the following names:

    bpp-seq-omicsConfig.cmake
    bpp-seq-omics-config.cmake

  Add the installation prefix of "bpp-seq-omics" to CMAKE_PREFIX_PATH or set
  "bpp-seq-omics_DIR" to a directory containing one of the above files.  If
  "bpp-seq-omics" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring incomplete, errors occurred!

Any clue???

**Comment by hbadrane** [comment]
I should add that all the files are in lib64/cmake/bpp-seq-omics3:
bpp-seq-omics3-config.cmake
bpp-seq-omics3-targets.cmake
bpp-seq-omics3-config-version.cmake
bpp-seq-omics3-targets-relwithdebinfo.cmake

**Comment by jydu** [comment]
Hi,

We are in the middle of an upgrade, the code on the master branch is therefore currently unstable. In order to compile the libraries, you need to use the latest stable version (2.4). Alternatively, if you need the most up-to-date and still compilable version, you can checkout and compile branches labeled 'rel299', this should solve the issue until version 3 is finally ready. Please do not hesitate to let me know if you need further assistance,

Julien.

**Comment by hbadrane** [comment]
Thank you. Yes using the rel299 was straightforward no errors.
